// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "belajar-go-echo/model"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: user
func (_m *UserRepository) CreateUser(user model.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUsers provides a mock function with given fields:
func (_m *UserRepository) GetAllUsers() ([]model.User, error) {
	ret := _m.Called()

	var r0 []model.User
	if rf, ok := ret.Get(0).(func() []model.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: input
func (_m *UserRepository) Login(input model.UserInput) model.User {
	ret := _m.Called(input)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(model.UserInput) model.User); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	return r0
}

// Register provides a mock function with given fields: input
func (_m *UserRepository) Register(input model.UserInput) model.User {
	ret := _m.Called(input)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(model.UserInput) model.User); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	return r0
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
